package dev.cjrv.azureversionator.theme

import androidx.compose.ui.graphics.Color

// --- LIGHT THEME (Clean, high-contrast professional) ---
val primaryLight = Color(0xFF0078D4) // Classic Azure
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDEECF9)
val onPrimaryContainerLight = Color(0xFF002050)
val secondaryLight = Color(0xFF2B2B2B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE1E1E1)
val onSecondaryContainerLight = Color(0xFF000000)
val tertiaryLight = Color(0xFF005A9E)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCFE4FA)
val onTertiaryContainerLight = Color(0xFF001832)
val errorLight = Color(0xFFD83B01)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFDE7E9)
val onErrorContainerLight = Color(0xFF420D06)
val backgroundLight = Color(0xFFF3F2F1)
val onBackgroundLight = Color(0xFF201F1E)
val surfaceLight = Color(0xFFFFFFFF)
val onSurfaceLight = Color(0xFF201F1E)
val surfaceVariantLight = Color(0xFFEDEBE9)
val onSurfaceVariantLight = Color(0xFF484644)
val outlineLight = Color(0xFF8A8886)
val outlineVariantLight = Color(0xFFC8C6C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2C313A)
val inverseOnSurfaceLight = Color(0xFFEDF1FA)
val inversePrimaryLight = Color(0xFFA8C8FF)
val surfaceDimLight = Color(0xFFEDEBE9)
val surfaceBrightLight = Color(0xFFFFFFFF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F2F1)
val surfaceContainerLight = Color(0xFFFAF9F8)
val surfaceContainerHighLight = Color(0xFFEDEBE9)
val surfaceContainerHighestLight = Color(0xFFE1DFDD)

// --- DARK THEME (Cyber-Azure / Tech-Focused) ---
val primaryDark = Color(0xFF00E5FF) // Electric Cyan
val onPrimaryDark = Color(0xFF00363D)
val primaryContainerDark = Color(0xFF004E58)
val onPrimaryContainerDark = Color(0xFFB2F5FF)
val secondaryDark = Color(0xFFD1D1D1) // Tech Grey
val onSecondaryDark = Color(0xFF1A1A1A)
val secondaryContainerDark = Color(0xFF333333)
val onSecondaryContainerDark = Color(0xFFE2E2E2)
val tertiaryDark = Color(0xFF7DE0FF)
val onTertiaryDark = Color(0xFF003544)
val tertiaryContainerDark = Color(0xFF004D62)
val onTertiaryContainerDark = Color(0xFFBFE9FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF050505) // Near Black
val onBackgroundDark = Color(0xFFE1E1E1)
val surfaceDark = Color(0xFF0A0A0A)
val onSurfaceDark = Color(0xFFE1E1E1)
val surfaceVariantDark = Color(0xFF1E1E1E)
val onSurfaceVariantDark = Color(0xFFC4C7C5)
val outlineDark = Color(0xFF444746)
val outlineVariantDark = Color(0xFF1E1E1E)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE1E1E1)
val inverseOnSurfaceDark = Color(0xFF1A1A1A)
val inversePrimaryDark = Color(0xFF006973)
val surfaceDimDark = Color(0xFF0A0A0A)
val surfaceBrightDark = Color(0xFF2B2B2B)
val surfaceContainerLowestDark = Color(0xFF000000)
val surfaceContainerLowDark = Color(0xFF0A0A0A)
val surfaceContainerDark = Color(0xFF121212)
val surfaceContainerHighDark = Color(0xFF1E1E1E)
val surfaceContainerHighestDark = Color(0xFF262626)
